name: Build and release Avg
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - ops   


jobs:
  build-release:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
        
      - name: Generate changelog
        run: |
          make changelog | tee -a changelog
          cat changelog
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build binary
        run: |
          make build

      - name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
           gh release create avg-${{ github.ref_name }}-x86_64 \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --notes-file changelog

  s2i-build:
    name: Build S2I Application Image
    runs-on: ubuntu-latest
    steps:
      # Install s2i
      - name: Install s2i
        run: |

               wget https://github.com/openshift/source-to-image/releases/download/v1.4.0/source-to-image-v1.4.0-d3544c7e-linux-386.tar.gz
               tar -xvf source-to-image-v1.4.0-d3544c7e-linux-386.tar.gz
               sudo mv s2i /usr/local/bin
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build S2I Image
        run: |
          sudo docker login quay.io -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }}
          sudo s2i build . quay.io/rh-ee-sakkulka/s2i-avg-builder quay.io/rh-ee-sakkulka/averagecalculator-app  
          sudo docker push quay.io/rh-ee-sakkulka/averagecalculator-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Authentication
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: rh-ee-sakkulka
          OPENSHIFT_NAMESPACE: rh-ee-sakkulka-dev
        with:
            openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
            openshift_username: ${{ env.OPENSHIFT_USER }}
            openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
            insecure_skip_tls_verify: false
            namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      - name: Deploy application
        run: |
            if oc get svc -l app=averagecalculator --ignore-not-found; then
                oc delete svc,deployment,route,imagestream --selector app=averagecalculator
                echo "deleted all resources with label app=averagecalculator";
            fi
            oc new-app quay.io/rh-ee-sakkulka/averagecalculator-app --name=averagecalculator --labels=app=averagecalculator,env=dev
            sleep 3
            oc expose svc averagecalculator --labels=averagecalculator
            oc get routes -l app=averagecalculator