name: create PR
on:
  workflow_dispatch:
  push:
    branches:
      - ops   

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Create Pull Request
        env:
          PR_TOKEN_ID: ${{ secrets.PR_TOKEN }} 
          
        run: |
          echo $PR_TOKEN_ID
          curl -X POST \
          -H "Authorization: token $PR_TOKEN_ID" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{
            "title": "Merge changes from ops to main",
            "head": "ops",  
            "base": "main",  
            "body": "This pull request merges changes from the ops branch into the main branch."
          }' \
          https://api.github.com/repos/Sakshi-Kulkarni/AverageCalculator/pulls
  
    build-metrix:
      runs-on: ${{ matrix.os }}
      continue-on-error: true
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          go-version: ['1.18', '1.19', '1.20']
          # architecture: [amd64, arm64]
          exclude:
            - os: windows-latest
              go-version: '1.18'
              architecture: arm64
            - os: macos-latest
              go-version: '1.19'
              architecture: amd64
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: ${{ matrix.go-version }}
  
        - name: Build
          run: |
            make build
  
        - name: Run tests
          run: |
            make test